### PR TITLE
Use the worpress roles API

### PR DESCRIPTION
**Pull request by klondi**
Use the worpress roles API to generate the options for the mappings and use these mappings to set the user role. For now the first found valid role is used.

### CODE REVIEW

**Comment by pitbulk** [comment]
@klondi 
Nice for that contribution, I will test it and publish a new version of the plugin that will include that improvements.

**Comment by klondi** [comment]
@pitbulk Found a bug where the default role would  be set when no role mapping is set it's fixed with this new push.

Also it makes it possible to set role precedences (so in case a user is in many groups and thus many role attributes are send, the user can choose which role should be used).

**Comment by pitbulk** [comment]
I contacted some customers that are using this plugin and they will be able to check if this new feature don't break anything.

I will wait till they give their ok. (it will take 1-2 weeks).

**Comment by klondi** [comment]
@pitbulk no worries, I'll be working on this project still for a few weeks so if they find any issue I'll be able to fix it :)

**Pull request merged**
